---           
- name: Change hostname to iot-gateway005
  hostname: name={{ gateway }}
              
             
              
- name: Create new file /etc/environment
  file: path=/etc/environment state=touch
              
- name: Install openvpn
  apt: name=openvpn state=present update_cache=yes  
  
- name: check if openvpn has been installed succesfully
  stat: path=/etc/openvpn
  register: check_path

- name: Configure the openvpn service to start automatically if /etc/openvpn exits
  lineinfile: backup=yes state=present dest=/etc/default/openvpn regexp='^#?AUTOSTART="all"' line=AUTOSTART="all"
  when: check_path.stat.exists
  
- name: Create subdirectory certs in /etc/openvpn/ if openvpn has been installed succesfully
  file: path=/etc/openvpn/certs state=directory group=root owner=root mode=700
  when: check_path.stat.exists

- name: check if /etc/openvpn/certs folder has been created successfully
  stat: path=/etc/openvpn/certs
  register: check_certs_folder     
  
    
  
- name: Install python3
  apt: name=python3 state=present 
  
  
- name: Install screen
  apt: name=screen state=present
  

# Walk through account creation, modification, and deletion
- name: Create a new user and add it to the group 'dialout' 
  user: name=iotuser groups=dialout password={{ password }} shell=/bin/bash home=/home/iotuser

- name: Add user 'iotuser' to sudoers file
  lineinfile: dest=/etc/sudoers state=present line='iotuser ALL=(ALL:ALL) ALL' validate='visudo -cf %s'

- name: Edit file /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp='^127.0.1.1'
  
- name: Edit file /etc/hosts
  lineinfile: dest=/etc/hosts state=present line='127.0.1.1         {{ gateway }}'

  
  
#- name: Reboot the server 
#  shell: sleep 2 && shutdown -r now 
#  async: 1
#  poll: 0
#  ignore_errors: true
      
#- name: waiting for server to comeback
#  local_action: wait_for host={{ inventory_hostname }} state=started port=22 delay=30 timeout=300 connect_timeout=15
  

- name: Remove user Pi
  user: name=ismael state=absent force=yes  
  
- name: Remove directory /home/pi
  file: path=/home/ismael state=absent
  
  
- name: Reboot the server again after removing user pi
  shell: sleep 2 && shutdown -r now 
  async: 1
  poll: 0
  ignore_errors: true
  become_user: root
  become: yes    
- name: waiting for server to comeback
  local_action: wait_for host={{ ansible_default_ipv4.address }} state=started port=22 delay=30 timeout=300 connect_timeout=15
    

      
