---
 - hosts: 192.168.0.105
   user: ismael
   become_user: root
   become: yes 
   vars: 
    foo: ' '
    option_line: '# Datei /etc/fstab\n
                    proc            /proc           proc    defaults              0 0\n
                    /dev/mmcblk0p1  /boot           vfat    ro,defaults           0 2\n
                    /dev/mmcblk0p2  /               ext4    ro,defaults,noatime   0 1\n
                    tmpfs           /var/log        tmpfs   nodev,nosuid          0 0\n
                    tmpfs           /var/tmp        tmpfs   nodev,nosuid          0 0\n
                    tmpfs           /tmp            tmpfs   nodev,nosuid          0 0\n
                 '   
   tasks:
   - name: update cache
     apt: update_cache=yes
   - name: remove cron
     apt: name=cron state=absent update_cache=yes purge=yes autoremove=yes
   - name: remove logrotate
     apt: name=logrotate state=absent purge=yes autoremove=yes
   - name: remove triggerhappy
     apt: name=triggerhappy state=absent purge=yes autoremove=yes
   - name: remove dphys-swapfile
     apt: name=dphys-swapfile state=absent purge=yes autoremove=yes
   - name: remove fake-hwclock
     apt: name=fake-hwclock state=absent purge=yes autoremove=yes
   - name: remove samba-common
     apt: name=samba-common state=absent purge=yes autoremove=yes
     
   - name: delete recursively directory /var/lib/dhcp/
     file: path=/var/lib/dhcp/ state=absent
     
   - name: delete recursively directory /var/spool 
     file: path=/var/spool  state=absent
   
   - name: delete recursively directory /var/lock
     file: path=/var/lock state=absent
        

   - name: create a symboliclink between /tmp and /var/lib/dhcp
     file: src=/tmp dest=/var/lib/dhcp state=link
     
   - name: create a symboliclink between /tmp and /var/spool
     file: src=/tmp dest=/var/spool state=link
     
   - name: create a symboliclink between /tmp and /var/lock
     file: src=/tmp dest=/var/lock state=link
     
   - name: create a symboliclink between /etc/resolv.conf and /tmp/resolv.conf
     file: src=/etc/resolv.conf dest=/tmp/resolv.conf state=link
     
   - name: delete old /etc/fstab
     file: path=/etc/fstab state=absent 
   - name: create new /etc/fstab
     copy: 
      dest: /etc/fstab 
      content: "{{ foo }}"
   - name: update /etc/fstab
     blockinfile:
       dest: /etc/fstab
       block: |
         # Datei /etc/fstab
         proc            /proc           proc    defaults              0 0
         /dev/mmcblk0p1  /boot           vfat    ro,defaults           0 2
         /dev/mmcblk0p2  /               ext4    ro,defaults,noatime   0 1
         tmpfs           /var/log        tmpfs   nodev,nosuid          0 0
         tmpfs           /var/tmp        tmpfs   nodev,nosuid          0 0
         tmpfs           /tmp            tmpfs   nodev,nosuid          0 0