---
 - hosts: 192.168.0.105
   su: yes
   su_user: root
  
   
   vars: 
    foo: ' '
    option_line: 'dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait fastboot noswap'
    
   tasks:
   #- name: update cache
   #  apt: update_cache=yes
   - name: update and upgrade all package
     apt: update_cache=yes upgrade=dist  
  
   #- name: check if proxy already configured
   #  stat: path=/etc/apt/apt.conf.d/95proxies
   #  register: check_path
     
   #- name: Create an empty file  /etc/apt/apt.conf.d/95proxies if file is not present
   #  file: path=/etc/apt/apt.conf.d/95proxies state=touch
   #  when: check_path.stat.exists=false

   #- name: Configure Apt Proxy
   #  blockinfile:
   #    dest: /etc/apt/apt.conf.d/95proxies
   #    block: |
   #      Acquire::http::proxy "http://pfde-extproxy.de.pepperl-fuchs.com:3128/";
   #  when: check_path.stat.exists=false
     
   #- name: Create new file /etc/environment if proxy not configured
   #  file: path=/etc/environment state=touch     
   #  when: check_path.stat.exists=false
     
   #- name: Update /etc/environment
   #  blockinfile:
   #    dest: /etc/environment
   #    block: |
   #      http_proxy=http://pfde-extproxy.de.pepperl-fuchs.com:3128 
   #  when: check_path.stat.exists=false
     
   - name: remove logrotate
     apt: name=logrotate state=absent purge=yes autoremove=yes
     
   - name: remove triggerhappy
     apt: name=triggerhappy state=absent purge=yes autoremove=yes
     
   - name: remove dphys-swapfile
     apt: name=dphys-swapfile state=absent purge=yes autoremove=yes
     
   - name: remove fake-hwclock
     apt: name=fake-hwclock state=absent purge=yes autoremove=yes
     
   - name: remove samba-common
     apt: name=samba-common state=absent purge=yes autoremove=yes
     
   - name: remove cron
     apt: name=cron state=absent purge=yes force=yes autoremove=yes
     
   - name: delete recursively directory /var/lib/dhcp/
     file: path=/var/lib/dhcp/ state=absent
     
   - name: delete recursively directory /var/spool 
     file: path=/var/spool  state=absent
   
   - name: delete recursively directory /var/lock
     file: path=/var/lock state=absent
        

   - name: create a symbolic link between /tmp and /var/lib/dhcp
     file: src=/tmp dest=/var/lib/dhcp state=link
     
   - name: create a symbolic link between /tmp and /var/spool
     file: src=/tmp dest=/var/spool state=link
     
   - name: create a symbolic link between /tmp and /var/lock
     file: src=/tmp dest=/var/lock state=link
     
   - name: create a symbolic link between /etc/resolv.conf and /tmp/resolv.conf
     file: src=/etc/resolv.conf dest=/tmp/resolv.conf state=link
     
   - name: delete old /etc/fstab
     file: path=/etc/fstab state=absent 
     
   - name: create new /etc/fstab
     copy: 
      dest: /etc/fstab 
      content: "{{ foo }}"
      
   - name: update /etc/fstab
     blockinfile:
       dest: /etc/fstab
       block: |
         # Datei /etc/fstab
         proc            /proc           proc    defaults              0 0
         /dev/mmcblk0p1  /boot           vfat    ro,defaults           0 2
         /dev/mmcblk0p2  /               ext4    ro,defaults,noatime   0 1
         tmpfs           /var/log        tmpfs   nodev,nosuid          0 0
         tmpfs           /var/tmp        tmpfs   nodev,nosuid          0 0
         tmpfs           /tmp            tmpfs   nodev,nosuid          0 0
         
   - name: delete old /boot/cmdline.txt
     file: path=/boot/cmdline.txt state=absent 
     
   - name: update /boot/cmdline.txt
     copy: 
      dest: /boot/cmdline.txt
      content: "{{ option_line }}"
      
      
   - name: Reboot the server 
     shell: sleep 2 && shutdown -r now 
     async: 1
     poll: 0
     become: yes
     become_user: root
     ignore_errors: true
         
   - name: waiting for server to comeback
     local_action: wait_for host={{ ansible_default_ipv4.address }} state=started port=22 delay=30 timeout=300 connect_timeout=15
       
