---
 - hosts: 192.168.0.105
   user: ismael
   become_user: root
   become: yes
   tasks:
   - name: install vim after updating the cache
     apt: update_cache=yes
   - name: install meld now
     apt: name=meld state=present
