---
 - hosts: 192.168.0.105
   user: ismael
   become_user: root
   become: yes
   vars: 
    foo: ' '
    option_line: '# Datei /etc/fstab\n
                    proc            /proc           proc    defaults              0 0\n
                    /dev/mmcblk0p1  /boot           vfat    ro,defaults           0 2\n
                    /dev/mmcblk0p2  /               ext4    ro,defaults,noatime   0 1\n
                    tmpfs           /var/log        tmpfs   nodev,nosuid          0 0\n
                    tmpfs           /var/tmp        tmpfs   nodev,nosuid          0 0\n
                    tmpfs           /tmp            tmpfs   nodev,nosuid          0 0\n
                 '
   tasks:
   - name: delete old /etc/fstab
     file: path=/etc/fstab state=absent 
   - name: create new /etc/fstab
     copy: 
      dest: /etc/fstab 
      content: "{{ foo }}"
   - name: update /etc/fstab
     blockinfile:
       dest: /etc/fstab
       block: |
         # Datei /etc/fstab
         proc            /proc           proc    defaults              0 0
         /dev/mmcblk0p1  /boot           vfat    ro,defaults           0 2
         /dev/mmcblk0p2  /               ext4    ro,defaults,noatime   0 1
         tmpfs           /var/log        tmpfs   nodev,nosuid          0 0
         tmpfs           /var/tmp        tmpfs   nodev,nosuid          0 0
         tmpfs           /tmp            tmpfs   nodev,nosuid          0 0
       

